### ISSUE TITLE
nc-cms Cross Site Scripting 

### ISSUE THREAD

**Issue by 0xMJ** [gnat/nc-cms#10]
Hello, I found that this cms may have some security problem
you can edit your html on http://localhost/nc-cms/nc-cms/index.php?action=edit_html&name=home_content
and you can Input any evil js you want
http://localhost/nc-cms/index.php?action=edit_html&name=home_contenta2ktk%3cimg%20src%3da%20onerror%3dalert(1)%3ejil8q
![image](https://user-images.githubusercontent.com/31585175/46939815-d52efc00-d099-11e8-92cd-1923fcc053d5.png)

**Comment by gnat** [comment]
@0xMJ Although very unlikely, this one is more plausible than your friend @Marblue's issue as it would require the attacker to phish the site administrator in some way. No regular users would be able to access this page.

Unlikely, but plausible, so congratulations. I'll go ahead and commit a low priority release for this one.

**Comment by gnat** [comment]
Resolved as a low priority fix in version 3.4
