### ISSUE TITLE
Multi user

### ISSUE THREAD

**Issue by susanadhikary** [gnat/nc-cms#2]
can u provide me the script for multi user fetching data from sql
or any solution for this

**Comment by Prolegomenes** [comment]
Hello,
I am surprised to do not find more activity on this platform.
Is there any forum where to ask questions and look users comments around ?
Thanks anyway to gave us such a cool CMS

**Comment by gnat** [comment]
No plans to implement multi-user at this time, although I'll certainly consider patches if anyone wants to undertake this functionality.

**Comment by jasper-e** [comment]
I'd appreciate multi-user support too. I can think about basic role support (like admin, editor, contributor, reader) plus API to require the right role. I am willing to contribute in php coding if needed.
