### ISSUE TITLE
Is there Platform and/or WebServer requirements ?

### ISSUE THREAD

**Issue by NetLancer** [gnat/nc-cms#3]
Hi there! The thing is example.php (nc-cms provided) seems doesn't work with me. I've got linux mint OS and lighttpd local server. Example.php (file) & nc-cms (folder) are placed in the root folder, but http://localhost/example.php gives only a blank screen, though to nc-cms(folder) I gave permissions 755. What have I missed?

**Comment by gnat** [comment]
@NetLancer there was a minor issue with the included example script which is now solved. Download the latest and it will work.

**Comment by NetLancer** [comment]
Thanx a lot, let me try

**Comment by gnat** [comment]
Fixed in latest.
