### ISSUE TITLE
error message about permissions

### ISSUE THREAD

**Issue by marathia** [gnat/nc-cms#5]
When I add a new editable content area in the HTML, I get error messages like:
> ERROR: Could not write file: home_content3. Make sure that this server has read and write permissions to the /nc-cms/content folder.

The new file (`/content/home_content3` in this example) is not created. 

The permissions to this folder are correct. Do I need to create the files for new editable content areas manually or is something else causing this error?

**Comment by MattWilsonMD** [comment]
I'm having the same issue with v3.2.2. I even tried giving the /content folder and all of its sub-files and directories full permissions, but nothing works.

**Comment by marathia** [comment]
Shamelessly 'bumping' this issue in the hope someone has a solution…

**Comment by gnat** [comment]
This is fixed now, apologies for the wait! @marathia @MattWilsonMD 

Grab the latest or use the Upgrading guide in README.md if you have an existing site.
