### ISSUE TITLE
Prevent login page from being indexed by search engines

### ISSUE THREAD

**Issue by marathia** [gnat/nc-cms#8]
When searching on Google for nc-cms, I found hundreds of nc-cms login pages in the results. 

I added `<meta name="robots" content="noindex, nofollow" />` to system/views/login.php to prevent this. It might be a good idea to include this (or any other measure) in the download.

**Comment by gnat** [comment]
This is actually how we currently get a rough idea of how many people use the project. People are welcome to disable it, or add a no robots.
